/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Backend */

#ifndef _Included_Backend
#define _Included_Backend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Backend
 * Method:    allocate
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_Backend_allocate
  (JNIEnv *, jobject, jint);

/*
 * Class:     Backend
 * Method:    fill
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_Backend_fill
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     Backend
 * Method:    linkMatrix
 * Signature: ()LCsrMatrix;
 */
JNIEXPORT jobject JNICALL Java_Backend_linkMatrix
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
